index:
    controller: App\Controller\HomeController::index
    path: /
controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
